name: mediconnect
description: "Medical appointment app connecting patients and doctors"
version: 1.3.1+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # HTTP Client
  dio: ^5.4.0
  
  # Navigation
  go_router: ^14.2.7
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Forms & Validation
  formz: ^0.7.0
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Utils
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true