name: mediconnect
description: "Medical appointment app connecting patients and doctors"
version: 1.1.0+1

environment:
  sdk: ^3.8.0  # Cambiado de >=3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # HTTP Client
  dio: ^5.4.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Utils
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true